---
title: Do your Worst
author: Allison Horst
date: '2019-04-28'
slug: do-your-worst
categories:
  - R
tags:
  - ggplot2
  - R
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
type: post
---

Clear and engaging data visualization is a critical part of science communication, and one that I emphasize in all courses I teach at the Bren School. So in the past, I've stressed the importance of customizing graphs to make them the best. 

Recently, I've realized value in adding exercises that require students to make their **worst**.

*Why is it sometimes __good__ to be so (intentionally) __bad__?*

Key word: *intentionally*. Creating a purposefully disgusting graph can promote learning in several useful ways: 

1. Making **the worst** graph encourages creativity
2. Making **the worst** graph requires extensive customization 
3. Making **the worst** graph makes us identify specific ways that a graph can be "bad"
4. Making **the worst** graph eliminates the stress of producing a perfect final product (...unless, of course, it's perfectly awful)
5. Making **the worst** graph is surprisingly freeing and fun



