---
title: Sharing (R lab) keys for success
author: Allison Horst
date: '2019-04-29'
slug: share-keys
categories:
  - R
  - teaching
tags:
  - R
description: ""
type: post
---

I just finished my sixth year of teaching intro stats and data analysis in R to environmental studies grad students. For the first five, I convinced myself that I shouldn't share my instructor code keys with students before weekly #rstats labs.

My commonly regurgitated (and baseless) excuses: 

> "If I share the key beforehand, no one will show up to labs!"

> "If I share the key beforehand, people will just run the key and not actively code along, so they won't learn as much!"

This year, a student was struggling to keep up in our computer labs and asked to get the instructor keys beforehand. We admittedly move pretty quickly in labs, and they wanted to look through code beforehand to increase their chances of keeping up. 

First I was like "eeeehhhhh," then I was like "pssshh fine I'll email it to you but please don't share it with anybody else because [see excuses above]," then eventually I was like "this is ridiculous let's see what happens if I share the instructor keys beforehand with everyone in the class."

Here is the nightmare that ensued: 

## 1. Everyone just still came to labs.

Seriously, attrition rate = zero. 

## 2. Everyone was still coding in labs. 

My sense was that most students didn't even look at the key despite knowing it was posted (also fine). But in each lab, several students had printed out the key as an additional resource to help them along. In short: the self-motivated students who benefitted from exploring lab keys beforehand *could*, and the rest just continued showing up and following along without it like they always had. 

I've realized there are actually **no down side** to posting my instructor code keys before labs. 

## In fact, there are clear benefits. Like: 

- If some students want to spend **more** time looking over code before labs, awesome!

- When students have to miss labs (illness, personal days, conferences, etc.) they know that the materials are all available without request - which means less stress and email for everyone.

- For anyone who *does* find themselves falling behind, there's always a key available for them to figure out where they got lost or went awry.

- It's actually **less** work for me. I can just push all materials to GitHub (data, lab templates, keys), without feeling like I have to hide pieces in different repos or folders or whatever. One (openly shared) Rproj to rule them all. 

## What DOES this require? 

When it comes down to it, I wasn't sharing instructor keys because I didn't have enough faith in my students. Which is really lame, because like 99.9% of the time they've only ever been *more* committed than I expect.

Believe that students are as awesome and dedicated as you want them to be - which, given then chance, they almost always are. Anyway, the students asking to review the lab materials beforehand are probably **not** the ones trying to weasel their way out of course effort. 

I'll continue posting all #rstats lab keys (heck, you can even see them): [ESM 206](https://github.com/allisonhorst/esm-206-2018) / [ESM 244](https://github.com/allisonhorst/esm-244-2019)), with gratitude to students who've repeatedly proven my reservations wrong. 


  